# Generated by Django 3.1.7 on 2021-03-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='seller',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
