# Generated by Django 3.1.7 on 2021-03-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='seller',
            field=models.CharField(default='Seller_test', max_length=100),
        ),
    ]
