# Generated by Django 3.1.7 on 2021-03-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210318_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('listing_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='seller',
            field=models.CharField(default='Default_Value', max_length=100),
        ),
    ]
