# Generated by Django 3.1.7 on 2021-04-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210409_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='current_price',
            field=models.IntegerField(null=True),
        ),
    ]
