# Generated by Django 3.1.7 on 2021-04-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionlisting_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
