# Generated by Django 3.1.7 on 2021-04-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auctionlisting_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='winner',
            field=models.CharField(default='Default_Value', max_length=100),
        ),
    ]
